server:
  port: 8082

compiler:
  docker:
    image:
      delete: ${DELETE_DOCKER_IMAGE:true} # delete the docker image at the end of the execution of the container, by default it's set to true.
  execution-memory:
    max: ${EXECUTION_MEMORY_MAX:10000}
    min: ${EXECUTION_MEMORY_MIN:0}
  execution-time:
    max: ${EXECUTION_TIME_MAX:15}
    min: ${EXECUTION_TIME_MIN:0}

spring:
  application:
    name: remote-code-compiler

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus